add property listing page
skilful522/Andersen-PropertyCross pull request #16
Opened 2020-01-04 12:57 UTC by skilful522

2020-01-08 13:30 UTC, kkamik commented on reducers/index.js
> -    searchedListReducer,
а для чего удалять редьюсер из 1й задачи?

2020-01-08 13:31 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        isFavorite: false,
а как компонент понимает, если ты из каталога зашел в избранную квартиру?

2020-01-09 10:41 UTC, skilful522 commented on reducers/index.js
> -    searchedListReducer,
исправил

2020-01-09 10:42 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        isFavorite: false,
Исправил. Буду прокидывать функцию, которая изменяет стейт и это решит проблему.

2020-01-09 11:46 UTC, kkamik commented on reducers/favoriteListReducer.js
> +function favoriteListReducer(state = initialState, action) {
action -> paylaod

2020-01-09 11:48 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        this.props.setIsFavorite(true);
1. поправить имя функции setIsFavorite. Например просто setFavorite(), и true передавать внутрь - странно. Я бы понял, если бы квартиру внутрь, но так оч странно

2020-01-09 11:48 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        this.props.addApartment({ ...this.props.location.apartmentInfo });
addApartment? Куда ты добавляешь?
Зачем спред, если там тот же объект?

2020-01-09 11:49 UTC, kkamik commented on src/components/PropertyListingPage/actions/addApartment.js
> +function addApartment(payload) {
ненужный экшен, такие экшены делать не надо. Просто диспатч вызови там где нужно

2020-01-14 12:42 UTC, kkamik commented on reducers/favoriteListReducer.js
> +function favoriteListReducer(state = initialState, action) {
задестракти type, payload

2020-01-16 08:31 UTC, kkamik commented on reducers/apartmentsListReducer.js
> +        case 'ADD_TO_FAVORITE_LIST':
в чем разница ADD_TO_FAVORITE_LIST и REMOVE_FROM_FAVORITE_LIST? Если нет разницы -> переименовать и дубликат удалитиь.

2020-01-16 08:34 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +            return { isFavorite: !state.isFavorite };
не так не пойдет. Надо хранить или в стейте, или в сторе.
Если надо хранить в сторе - просто делай селектор (там где mapState делаешь функцию в которую передаешь стор и она тебе возвращает флаг о том, если ли бумага в избранном или нет)

2020-01-16 08:35 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        isApartmentInStorage(currentApartment).then((result) => {
это уйдет как только сделаешь 1 источник правды.
https://github.com/skilful522/Andersen-PropertyCross/pull/16/files#r367288311

2020-01-16 08:36 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        if (!currentApartment) {
логика супер, сначала сам создаешь объект, а потом делаешь проверку
!{}

Тоесть эта штука никогда не сработает. Тут что-то не так с кодом.

2020-01-16 08:36 UTC, kkamik commented on src/components/PropertyListingPage/actions/addToFavoriteList.js
> +            result ? removeApartmentFromFavList(payload) : addApartmentToFavList(payload);
или ты можешь просто хранить список избранного, а селектором в компоненте понимать, твоя квартира в этом списке или нет. И не надо будет стремных диспатчей.

2020-01-16 08:36 UTC, kkamik commented on src/components/PropertyListingPage/actions/removeApartmentFromFavList.js
> +    getLocalStorage('favoriteList').then((list) => {
return

2020-01-16 08:37 UTC, kkamik commented on src/components/PropertyListingPage/actions/removeApartmentFromFavList.js
> +        setLocaleStorage('favoriteList', favoriteList);
return

2020-01-16 08:37 UTC, kkamik commented on src/components/SearchResultsPage/actions/getApartmentsList.js
> +                payload: data,
почему ты иногда передаешь payload, а иногда передаешь данные? Приведи все к 1 виду.
Либо везде payload, либо везде называй по сущностям.

2020-01-16 08:38 UTC, kkamik commented on src/components/SearchResultsPage/components/ApartmentsList/ApartmentsList.js
> +            .getApartmentsList({ city: this.props.match.params.location, page: this.props.currentPage + 1 })
this.props. используется более 1 раза(2 или 3)
=> сделай деструктуризацию.

2020-01-16 08:40 UTC, kkamik commented on src/utils/isApartmentInStorage.js
> +function isApartmentInStorage(apartment) {
название функции суперстранное.
квартира в месте_хранения? Что? Ты же проверяешь о том, если ли она в списке избранного. Так и называй соответственно.

2020-01-17 07:05 UTC, skilful522 commented on reducers/apartmentsListReducer.js
> +        case 'ADD_TO_FAVORITE_LIST':
Исправил

2020-01-17 07:07 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +            return { isFavorite: !state.isFavorite };
Храню isFavorite в стейте, на клик проверяю если находится текущая страница в favorite list

2020-01-17 07:08 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        isApartmentInStorage(currentApartment).then((result) => {
Не исправил. Логика: проверяю находится ли текущая страница в favorite list и в зависимости от флага устанавливаю значение isFavorite.

2020-01-17 07:10 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        if (!currentApartment) {
Исправил. Правда, какая-то глупость =) Забыл удалить. Использовал это для теста, когда был баг с пропсами

2020-01-17 07:11 UTC, skilful522 commented on src/components/PropertyListingPage/actions/addToFavoriteList.js
> +            result ? removeApartmentFromFavList(payload) : addApartmentToFavList(payload);
Не исправил. Тут происходит логика добавления или удаления из favorite list.
Могу вообще убрать этот экшен и сделать это утилитой.

2020-01-17 07:11 UTC, skilful522 commented on src/components/PropertyListingPage/actions/removeApartmentFromFavList.js
> +    getLocalStorage('favoriteList').then((list) => {
Исправил

2020-01-17 07:11 UTC, skilful522 commented on src/components/PropertyListingPage/actions/removeApartmentFromFavList.js
> +        setLocaleStorage('favoriteList', favoriteList);
Исправил

2020-01-17 07:11 UTC, skilful522 commented on src/components/SearchResultsPage/actions/getApartmentsList.js
> +                payload: data,
Исправил

2020-01-17 07:11 UTC, skilful522 commented on src/components/SearchResultsPage/components/ApartmentsList/ApartmentsList.js
> +            .getApartmentsList({ city: this.props.match.params.location, page: this.props.currentPage + 1 })
Исправил

2020-01-17 07:11 UTC, skilful522 commented on src/utils/isApartmentInStorage.js
> +function isApartmentInStorage(apartment) {
Исправил

2020-01-17 07:24 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        apartmentInFavoriteList(currentApartment).then((result) => {
мм, и в итоге у тебя все равно 2 источника правды. Даже 3. В сторе, в LS и в стейте.
1. Надо сделать чтобы список избранного был в LS.
2. Чтобы ты запрашивал список избранного 1 раз (весь список) и складывал в стор.
3. Сделал селектор, который бы смотрел в стор и понимал, есть ли там необходимая квартира.
4. В случае, когда ты удаляешь или добавляешь элемент в избранное, у тебя обновляется список избранного -> ты обновляешь стор -> компонент узнает об изменении состояния из пропсов.

2020-01-17 13:58 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        apartmentInFavoriteList(currentApartment).then((result) => {
Исправил

2020-01-17 14:08 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        this.props.apartmentInFavoriteList(currentApartment);
сомнительно.
На каталоге избранного я бы запрашивал список избранного и все.
Потом смотрел бы селектором в стор и определял конкретно мой элемент есть в списке или нет.
А пока нету списка - в рендере рендерил бы лоаедер.

2020-01-17 14:09 UTC, kkamik commented on src/components/PropertyListingPage/actions/addApartmentToFavList.js
> +            setLocaleStorage('favoriteList', [...favoriteList, apartment]);
а стор обновить не нужно? Как компонент узнает, что стор обновлися?

2020-01-17 14:09 UTC, kkamik commented on src/components/PropertyListingPage/actions/updateFavoriteList.js
> +function updateFavoriteList(payload) {
класс, экшен называется updateFavoriteList, но внутри ты по каким-то причинам удаляешь или добавляешь в избранное оО

2020-01-20 12:44 UTC, skilful522 commented on src/components/PropertyListingPage/actions/updateFavoriteList.js
> +function updateFavoriteList(payload) {
Исправил

2020-01-20 12:44 UTC, skilful522 commented on src/components/PropertyListingPage/actions/addApartmentToFavList.js
> +            setLocaleStorage('favoriteList', [...favoriteList, apartment]);
Исправил

2020-01-20 12:44 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        this.props.apartmentInFavoriteList(currentApartment);
Исправил

2020-01-20 13:19 UTC, kkamik commented on reducers/apartmentsListReducer.js
> +        case 'GET_FAVORITE_LIST':
дублирование

2020-01-20 13:20 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPage.js
> +function selector(store) {
selectSmthing()
selectCats()
selectDogs()

2020-01-20 13:21 UTC, kkamik commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        setCurrentApartment(this.props.location.apartmentInfo);
PropertyListingPagePure разве отвечает не за общий список квартир? Ты уверен, что setCurrentApartment вообще уместно тут?

2020-01-20 13:22 UTC, kkamik commented on src/components/PropertyListingPage/actions/removeApartmentFromFavList.js
> +            dispatch({
set().then(() => dispatch)

2020-01-20 13:22 UTC, kkamik commented on src/components/PropertyListingPage/actions/getFavoriteList.js
> +            dispatch({ type: 'GET_FAVORITE_LIST', payload });
return

2020-01-20 13:22 UTC, kkamik commented on src/components/PropertyListingPage/actions/addApartmentToFavList.js
> +                setLocaleStorage('favoriteList', [...favoriteList, apartment]);
set().then(() => dispatch)

2020-01-20 13:22 UTC, kkamik commented on src/utils/isApartmentInFavoriteList.js
> +function isApartmentInFavoriteList(apartment) {
этот экшен все еще нужен? Если нет - удали.

2020-01-20 14:39 UTC, skilful522 commented on reducers/apartmentsListReducer.js
> +        case 'GET_FAVORITE_LIST':
Исправил

2020-01-20 14:40 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPage.js
> +function selector(store) {
Исправил

2020-01-20 14:40 UTC, skilful522 commented on src/components/PropertyListingPage/PropertyListingPagePure.js
> +        setCurrentApartment(this.props.location.apartmentInfo);
Исправил

2020-01-20 14:40 UTC, skilful522 commented on src/components/PropertyListingPage/actions/removeApartmentFromFavList.js
> +            dispatch({
Исправил

2020-01-20 14:40 UTC, skilful522 commented on src/components/PropertyListingPage/actions/getFavoriteList.js
> +            dispatch({ type: 'GET_FAVORITE_LIST', payload });
Исправил

2020-01-20 14:40 UTC, skilful522 commented on src/components/PropertyListingPage/actions/addApartmentToFavList.js
> +                setLocaleStorage('favoriteList', [...favoriteList, apartment]);
Исправил

2020-01-20 14:40 UTC, skilful522 commented on src/utils/isApartmentInFavoriteList.js
> +function isApartmentInFavoriteList(apartment) {
Исправил

2020-01-21 07:13 UTC, kkamik commented on reducers/favoriteListReducer.js
> +        case 'UPLOAD_CURRENT_APARTMENT':
это ж тоже сущность не имеет отношения к избранному.
надо вынести в отдельный редьюсер.

и переименовать эвент
ЧТО-ТО_ГЛАГОЛ

CURRENT_APPARTMENT_LOADED

2020-01-21 07:14 UTC, kkamik commented on src/components/ApartmentPage/ApartmentPagePure.js
> +        uploadCurrentApartment(this.props.location.apartmentInfo);
ну ало, upload? ты ее загружаешь?
fetchCurrentAppartment

2020-01-21 07:15 UTC, kkamik commented on src/components/ApartmentPage/actions/addApartmentToFavList.js
> +                setLocaleStorage('favoriteList', [...favoriteList, apartment]).then(() => {
return

2020-01-21 07:15 UTC, kkamik commented on src/components/ApartmentPage/actions/addApartmentToFavList.js
> +                    dispatch({
return

2020-01-21 07:15 UTC, kkamik commented on src/components/ApartmentPage/actions/getFavoriteList.js
> +            dispatch({ type: 'UPDATE_FAVORITE_LIST', payload });
return

2020-01-21 07:15 UTC, kkamik commented on src/components/ApartmentPage/actions/removeApartmentFromFavList.js
> +                dispatch({
return

2020-01-21 07:48 UTC, skilful522 commented on reducers/favoriteListReducer.js
> +        case 'UPLOAD_CURRENT_APARTMENT':
Исправил

2020-01-21 07:48 UTC, skilful522 commented on src/components/ApartmentPage/ApartmentPagePure.js
> +        uploadCurrentApartment(this.props.location.apartmentInfo);
Исправил

2020-01-21 07:48 UTC, skilful522 commented on src/components/ApartmentPage/actions/addApartmentToFavList.js
> +                setLocaleStorage('favoriteList', [...favoriteList, apartment]).then(() => {
Исправил

2020-01-21 07:48 UTC, skilful522 commented on src/components/ApartmentPage/actions/addApartmentToFavList.js
> +                    dispatch({
Исправил

2020-01-21 07:49 UTC, kkamik commented on src/components/ApartmentPage/ApartmentPage.js
> +    return { isAdded: selectFavoriteApartment(favoriteListReducer, apartmentsListReducer) };
isAdded - boolean.
1. selectFavoriteApartment - ожидается, что ты вернешь отсюда объект. Надо переименовать селектор в данном случае либо возвращать объект из него.

2. Активную квартиру лучше понимать не из стора, а из урла, ибо в сторе у тебя могут лежать старые данные.

2020-01-21 07:49 UTC, skilful522 commented on src/components/ApartmentPage/actions/getFavoriteList.js
> +            dispatch({ type: 'UPDATE_FAVORITE_LIST', payload });
Исправил

2020-01-21 07:49 UTC, skilful522 commented on src/components/ApartmentPage/actions/removeApartmentFromFavList.js
> +                dispatch({
Исправил

2020-01-21 07:50 UTC, kkamik commented on src/components/ApartmentPage/actions/addApartmentToFavList.js
> +        getLocalStorage('favoriteList').then((favoriteList) => {
return

2020-01-23 07:17 UTC, skilful522 commented on src/components/ApartmentPage/ApartmentPage.js
> +    return { isAdded: selectFavoriteApartment(favoriteListReducer, apartmentsListReducer) };
Исправил

2020-01-23 07:18 UTC, skilful522 commented on src/components/ApartmentPage/actions/addApartmentToFavList.js
> +        getLocalStorage('favoriteList').then((favoriteList) => {
Исправил

2020-01-23 07:49 UTC, kkamik commented on src/utils/makeApartmentId.js
> +const makeApartmentId = (imgUrl) => imgUrl.replace(/[^1-9]/g, '');
ток ты ничего не make тут.
Поэтому лучше назвать getAppartmentId или как-то аналогично.

2020-01-23 07:51 UTC, skilful522 commented on src/utils/makeApartmentId.js
> +const makeApartmentId = (imgUrl) => imgUrl.replace(/[^1-9]/g, '');
Исправил

2020-01-23 08:11 UTC, kkamik approved these changes

2020-01-23 08:11 UTC, kkamik requested changes
stop

2020-01-23 08:12 UTC, kkamik commented on src/components/ApartmentPage/actions/fetchCurrentApartment.js
> +    let currentApartmentId;
не, так не пойдет, тут чето странно происходит

2020-01-23 08:13 UTC, kkamik commented on src/components/ApartmentPage/actions/fetchCurrentApartment.js
> +            const currentApartment = listings.find((apartment) => {
1. у тебя id есть в payload.
2. зачем тебе доп переменная, если у тебя она уже есть?

2020-01-23 08:23 UTC, skilful522 commented on src/components/ApartmentPage/actions/fetchCurrentApartment.js
> +    let currentApartmentId;
Исправил

2020-01-23 08:25 UTC, skilful522 commented on src/components/ApartmentPage/actions/fetchCurrentApartment.js
> +            const currentApartment = listings.find((apartment) => {
Исправил

2020-01-23 08:27 UTC, kkamik approved these changes

2020-01-23 08:27 UTC, merged